---

- name: Install packages
  yum: name={{ item }} state=present
  with_items:
    - "@Development tools" 
    - "@System administration tools"
    - "@Python"
    - "@Perl Support"
    - "@Networking Tools"
    - "@MySQL Database client"
    - "@TeX support"
    - "@Haskell"
    - "@Emacs"
    - "@Core"
    - "@Compatibility libraries"
    - "@Buildsystem building group"
    - "atop"
    - "rclone"
    - "s3cmd"
    - "strace"
